### ISSUE TITLE
Volume controls: when you search for a new song and select one it doesn't persist the volume change

### ISSUE THREAD

**Issue by mjhult** [WVAviator/music-browser-cli#20]

**Comment by WVAviator** [comment]
This is possibly because choosing a new song via search creates a new video element and therefore the old canplay event subscription is obsolete.

Perhaps listening for the video element via a childList MO on its parent and creating a new event subscription when it changes is the fix.

**Comment by WVAviator** [comment]
The fix for this and for other issues with volume not persisting is using the following code in place of setting the video.volume directly:
```
const volumeSlider = document.querySelector('#volume-slider');
volumeSlider.value = 10;
volumeSlider.dispatchEvent(new Event('change'));
```
This will need to occur in a page.evaluate() function since it's a DOM process and not a Node process. In full it should be something similar to: 
```
await page.evaluate((volume) => {
    const volumeSlider = document.querySelector('#volume-slider');
    volumeSlider.value = Math.floor(volume * 100);
    volumeSlider.dispatchEvent(new Event('change'));
}, this.volume);
```

**Comment by mjhult** [comment]
https://github.com/WVAviator/music-browser-cli/pull/23
